### ISSUE TITLE
codestyle

### ISSUE THREAD

**Issue by sakulstra** [Meteor-Mentor/meteor_mentor#9]
Including some eslint(for example https://github.com/mantrajs/mantra-sample-blog-app/blob/master/.eslintrc) would be nice.
So we have at least a common code style and can make an introduction into ci services.

**Comment by serkandurusoy** [comment]
+1

**Comment by bearcanrun** [comment]
+1. I haven't worked with many coding teams and from conversations, it sounds like quite a few of the members don't either on a regular basis. Any good resources for "Team Coding and Practices for Newbies"?

**Comment by sakulstra** [comment]
@bearcanrun , actually there isn't anything you have to learn, except for some eslint and even this is optional. When using sth. like eslint a modern editor will show you when your doing sth. wrong (wrong in terms of "no empty line at the end of a file", or "a line shouldn't be longer than 80 chars") - with eslint setup via ci all contributors are "forced" to use the same coding standards which increases readability - nothing else.

**Comment by necmettin** [comment]
considering we have and `.eslintrc` in the repo, close this?
